#!/bin/bash
#
# Copyright (C) 2009  Jonas Bernoulli
#
# Author: Jonas Bernoulli <jonas@bernoul.li>
# Created: 20090621
# Updated: 20090621
# Version: 0.1
# Homepage: https://github.com/tarsius/xmonad.el
#
# Commentary:
usage () { cat <<EOF
emonad-0.1 -- Access the Emacs minibuffer frame using emacsclient.

usage: emonad [-i SEXP]
   or: emonad -e|-f
   or: emonad -h|--help

options:
   -i SEXP    Interactively call SEXP
   -e         Interactively call command execute-extended-command
   -f         Interactively call command find-file-other-frame
   -h|--help  Show this information

With no options only focus the dedicated minibuffer frame.
EOF
exit
}
# xdotool is required and it is assumed that a dedicated minibuffer
# frame exists.  Also this script was only tested with Xmonad and
# might not work as expected with other window managers.
#
# This script is currently broken in that it never prints anything to
# standard out, making it useless as a pager.  It seams it is not
# possible for emacsclient to (1) print to stout and at the same
# time return even when the user aborts reading from the minibuffer.

MINIBUF=$(xdotool search --title ${EMONAD_MINIBUF:-"\\*Minibuf-0\\*"})
PREVWIN=$(xdotool getwindowfocus)

case $1 in
-h|--help) usage ;;
-i) SEXP="(call-interactively '$2)" ;;
-e) SEXP="(call-interactively 'execute-extended-command)" ;;
-f) SEXP="(call-interactively 'find-file-other-frame)" ;;
'') SEXP="nil"; KEEP_FOCUS=t ;;
*)  SEXP="$1" ;;
esac

STRING=$(emacsclient -e "\
(let ((emonad-completions t)
      (emonad-client (car server-clients)))
  (select-frame-set-input-focus default-minibuffer-frame)
  (unwind-protect $SEXP
    (when (memq emonad-client server-clients)
      (server-delete-client emonad-client t))))")
STATUS=$?

echo ${STRING:1:$((${#STRING}-2))}

if [[ -n "$PREVWIN" \
   && -z "$KEEP_FOCUS" \
   && "$(xdotool getwindowfocus 2> /dev/null)" == "$MINIBUF" ]]
then
    xdotool windowfocus $PREVWIN 2> /dev/null
fi

exit $STATUS
