#!/bin/bash
#
# Copyright (C) 2009  Jonas Bernoulli
#
# Author: Jonas Bernoulli <jonas@bernoul.li>
# Created: 20090621
# Updated: 20091112
# Version: 0.1+
# Homepage: https://github.com/tarsius/xmonad.el
#
# Commentary:
usage () { cat <<EOF
emonad-0.1 -- Access the Emacs minibuffer frame using emacsclient.

usage: emonad [-i SEXP]
   or: emonad -e|-f
   or: emonad -h|--help

options:
   -i SEXP    Interactively call SEXP
   -e         Interactively call command execute-extended-command
   -f         Interactively call command find-file-other-frame
   -h|--help  Show this information

With no options only focus the dedicated minibuffer frame.
EOF
exit
}

MINIBUF=$(xdotool search --title ${EMONAD_MINIBUF:-"\\*Minibuf-0\\*"})
PREVWIN=$(xdotool getwindowfocus)

case $1 in
-h|--help) usage ;;
-i) SEXP="(call-interactively '$2)" ;;
-e) SEXP="(call-interactively 'execute-extended-command)" ;;
-f) SEXP="(call-interactively 'find-file-other-frame)" ;;
'') SEXP="nil"; KEEP_FOCUS=t ;;
*)  SEXP="$1" ;;
esac

xdotool windowfocus $MINIBUF
OUTPUT=$(emacsclient -e "\
(let ((emonad-completions t)
      (emonad-client (car server-clients))
      (minibuffer-auto-raise t))
  (condition-case nil $SEXP
    (quit (when (memq emonad-client server-clients)
            (server-delete-client emonad-client t)))))")
STATUS=$?

echo ${OUTPUT:1:$((${#OUTPUT}-2))}

if [[ -n "$PREVWIN" \
   && -z "$KEEP_FOCUS" \
   && "$(xdotool getwindowfocus 2> /dev/null)" == "$MINIBUF" ]]
then
    xdotool windowfocus $PREVWIN 2> /dev/null
fi

exit $STATUS
